import "dart:ui";
import "package:my_beer_diary/model/beer.dart";

const List<String> breweryNames = [
  "Agent",
  "Albert Michler",
  "Albrecht",
  "Antonín",
  "Antoš",
  "Bad Flash",
  "Bakalář",
  "Beer Factory",
  "Beran",
  "Bernard",
  "Bezák",
  "Bitches Brew",
  "Bizon",
  "Born",
  "Braník",
  "Brewteam",
  "Břevnov",
  "Březňák",
  "Budulínek",
  "Budweiser Budvar",
  "Clock",
  "Cobolis",
  "Crazy Clown",
  "Cvikov",
  "Čestmír",
  "Černá Hora",
  "Černý Potoka",
  "Čtyři lípy",
  "Dobruška",
  "Dobřany",
  "Dráteník",
  "Duck and Dog",
  "Elektrárna",
  "Excelent",
  "Falkenštejn",
  "Falkon",
  "Fenetra",
  "Frankies",
  "Funky Fluid",
  "Gambrinus",
  "GARP",
  "Hangár",
  "Hákův parní pivovar",
  "Hauskrecht",
  "Heineken",
  "Hellstork",
  "Hendrych",
  "Herold",
  "Holba",
  "Holendr",
  "Hoppy Dog",
  "Hostomice",
  "Hroch",
  "Hubertus",
  "Chomout",
  "Chotěšov",
  "Chotoviny",
  "Chroust",
  "ISAO",
  "Ježek",
  "Jungberg",
  "Kamenice",
  "Klasik",
  "Klášter",
  "Klenot",
  "Knajzl",
  "Kocour",
  "Kočovný Kozi",
  "Kojetín",
  "Konrad",
  "Kosa Prérií",
  "Kostelec",
  "Kotouč",
  "Kounice",
  "Kousek Piva",
  "Kozel",
  "Kozlíček Dubenky",
  "Krakonoš",
  "Krasavec",
  "Kristýna",
  "Kročehlavy",
  "Krušnohor",
  "Krušovice",
  "Křemenný Vrch",
  "Křikloun",
  "Kvasar",
  "Labuť",
  "Litovel",
  "Lípák",
  "Lobkowicz",
  "Lomnice",
  "Mad Cat",
  "Malešov",
  "Matuška",
  "Master",
  "Mazák",
  "Máša",
  "Medvěd",
  "Mlýn",
  "Moravia",
  "Mordýř",
  "Muflon",
  "Nachmelená Opice",
  "Nepomucen",
  "Nomád",
  "Novopacké",
  "Nový rybník",
  "Nozib",
  "Obora",
  "Olešná",
  "Opat",
  "O.SKAR",
  "Ostravar",
  "Ovipistán",
  "Pardál",
  "Paskov",
  "Perlová Voda",
  "Pernštejn",
  "Pilsner Urquell",
  "Pinta",
  "Pioneer",
  "Pivečka",
  "Platan",
  "Plzeňský Bandita",
  "Poděbradský Zdroj",
  "Podklášterní Urban",
  "Podřipské",
  "Polička",
  "Postřižiny",
  "Potmehúd",
  "Poutník",
  "Proud",
  "Primátor",
  "Primus",
  "Purkmistr",
  "Radegast",
  "Radouš",
  "Raven",
  "Rebel",
  "Rockmill",
  "Rohozec",
  "Rudohor",
  "Rychtář",
  "Řeporyje",
  "Samson",
  "Sibeeria",
  "SQBRU",
  "Starobrno",
  "Staropramen",
  "Stella Artois",
  "Stín",
  "Strahov",
  "Svatý Ján",
  "Svatý Petr",
  "Svijany",
  "Šepťák",
  "Švihov",
  "Tambor",
  "The Barn Beer co.",
  "Thrills",
  "Továrna",
  "Topolský",
  "Trilobit",
  "Třebonický Rukodělný",
  "U Fleků",
  "U Medvídků",
  "U Vacků",
  "Únětice",
  "Vagabund",
  "Valášek",
  "Valeč",
  "Valteřickej Strojník",
  "Veselka",
  "Vik",
  "Vinohradská",
  "Vinohradský Démon",
  "Volt",
  "Všerad",
  "Welzl",
  "Wywar",
  "Záhora",
  "Zdislavka",
  "Zhůřák",
  "Zichovec",
  "Zlatopramen",
  "Zlatý Bažant",
  "Zloun z Loun",
  "Zlosyn z Losin",
  "Znojemský Městský",
  "Zubr",
  "Zvíkov",
  "Žatec",
  "Židovice",
  "Žlebské Chvalovice",
];

const beerColorStraw = Color(0xfff3eb8f);
const beerColorGold = Color(0xfffec95a);
const beerColorAmber = Color(0xffd67100);
const beerColorBrown = Color(0xff8d4c32);
const beerColorDark = Color(0xff1e0204);
const beerColorRed = Color(0xffba0109);
const beerColorGreen = Color(0xff5bba01);

const List<Color> beerColors = [
  beerColorStraw,
  beerColorGold,
  beerColorAmber,
  beerColorBrown,
  beerColorDark,
  beerColorRed,
  beerColorGreen,
];

const _beerColorStrawStr = "f3eb8f";
const _beerColorGoldStr = "fec95a";
const _beerColorAmberStr = "d67100";
const _beerColorBrownStr = "8d4c32";
const _beerColorDarkStr = "1e0204";
const _beerColorRedStr = "ba0109";
const _beerColorGreenStr = "5bba01";

const List<Beer> defaultBeers = [
  Beer(
    breweryName: "Beran",
    description: "Lehký ALE",
    epm: 10.0,
    abv: 4.5,
    color: _beerColorAmberStr,
  ),
  Beer(
    breweryName: "Beran",
    description: "Jedenáctka",
    epm: 11.0,
    abv: 4.5,
    color: _beerColorGoldStr,
  ),
  Beer(
    breweryName: "Beran",
    description: "Polotmavá dvanáctka",
    epm: 12.0,
    abv: 5.0,
    color: _beerColorBrownStr,
  ),
  Beer(
    breweryName: "Bernard",
    description: "Desítka",
    epm: 10.0,
    abv: 3.8,
    color: _beerColorGoldStr,
  ),
  Beer(
    breweryName: "Bernard",
    description: "Jedenáctka",
    epm: 11.0,
    abv: 4.5,
    color: _beerColorGoldStr,
  ),
  Beer(
    breweryName: "Bernard",
    description: "Kvasnicová jedenáctka",
    epm: 11.0,
    abv: 4.6,
    color: _beerColorGoldStr,
  ),
  Beer(
    breweryName: "Beran",
    description: "Dvanáctka",
    epm: 12.0,
    abv: 4.9,
    color: _beerColorGoldStr,
  ),
];
