import "dart:ui";

const List<String> breweryNames = [
  "Agent",
  "Albert Michler",
  "Albrecht",
  "Antonín",
  "Antoš",
  "Bad Flash",
  "Bakalář",
  "Beer Factory",
  "Beran",
  "Bernard",
  "Bezák",
  "Bitches Brew",
  "Bizon",
  "Born",
  "Braník",
  "Brewteam",
  "Břevnov",
  "Březňák",
  "Budulínek",
  "Budweiser Budvar",
  "Clock",
  "Cobolis",
  "Crazy Clown",
  "Cvikov",
  "Čestmír",
  "Černá Hora",
  "Černý Potoka",
  "Čtyři lípy",
  "Dobruška",
  "Dobřany",
  "Dráteník",
  "Duck and Dog",
  "Elektrárna",
  "Excelent",
  "Falkenštejn",
  "Falkon",
  "Fenetra",
  "Frankies",
  "Funky Fluid",
  "Gambrinus",
  "GARP",
  "Hangár",
  "Hákův parní pivovar",
  "Hauskrecht",
  "Heineken",
  "Hellstork",
  "Hendrych",
  "Herold",
  "Holba",
  "Holendr",
  "Hoppy Dog",
  "Hostomice",
  "Hroch",
  "Hubertus",
  "Chomout",
  "Chotěšov",
  "Chotoviny",
  "Chroust",
  "ISAO",
  "Ježek",
  "Jungberg",
  "Kamenice",
  "Klasik",
  "Klášter",
  "Klenot",
  "Knajzl",
  "Kocour",
  "Kočovný Kozi",
  "Kojetín",
  "Konrad",
  "Kosa Prérií",
  "Kostelec",
  "Kotouč",
  "Kounice",
  "Kousek Piva",
  "Kozel",
  "Kozlíček Dubenky",
  "Krakonoš",
  "Krasavec",
  "Kristýna",
  "Kročehlavy",
  "Krušnohor",
  "Krušovice",
  "Křemenný Vrch",
  "Křikloun",
  "Kvasar",
  "Labuť",
  "Litovel",
  "Lípák",
  "Lobkowicz",
  "Lomnice",
  "Mad Cat",
  "Malešov",
  "Matuška",
  "Master",
  "Mazák",
  "Máša",
  "Medvěd",
  "Mlýn",
  "Moravia",
  "Mordýř",
  "Muflon",
  "Nachmelená Opice",
  "Nepomucen",
  "Nomád",
  "Novopacké",
  "Nový rybník",
  "Nozib",
  "Obora",
  "Olešná",
  "Opat",
  "O.SKAR",
  "Ostravar",
  "Ovipistán",
  "Pardál",
  "Paskov",
  "Perlová Voda",
  "Pernštejn",
  "Pilsner Urquell",
  "Pinta",
  "Pioneer",
  "Pivečka",
  "Platan",
  "Plzeňský Bandita",
  "Poděbradský Zdroj",
  "Podklášterní Urban",
  "Podřipské",
  "Polička",
  "Postřižiny",
  "Potmehúd",
  "Poutník",
  "Proud",
  "Primátor",
  "Primus",
  "Purkmistr",
  "Radegast",
  "Radouš",
  "Raven",
  "Rebel",
  "Rockmill",
  "Rohozec",
  "Rudohor",
  "Rychtář",
  "Řeporyje",
  "Samson",
  "Sibeeria",
  "SQBRU",
  "Starobrno",
  "Staropramen",
  "Stella Artois",
  "Stín",
  "Strahov",
  "Svatý Ján",
  "Svatý Petr",
  "Svijany",
  "Šepťák",
  "Švihov",
  "Tambor",
  "The Barn Beer co.",
  "Thrills",
  "Továrna",
  "Topolský",
  "Trilobit",
  "Třebonický Rukodělný",
  "U Fleků",
  "U Medvídků",
  "U Vacků",
  "Únětice",
  "Vagabund",
  "Valášek",
  "Valeč",
  "Valteřickej Strojník",
  "Veselka",
  "Vik",
  "Vinohradská",
  "Vinohradský Démon",
  "Volt",
  "Všerad",
  "Welzl",
  "Wywar",
  "Záhora",
  "Zdislavka",
  "Zhůřák",
  "Zichovec",
  "Zlatopramen",
  "Zlatý Bažant",
  "Zloun z Loun",
  "Zlosyn z Losin",
  "Znojemský Městský",
  "Zubr",
  "Zvíkov",
  "Žatec",
  "Židovice",
  "Žlebské Chvalovice",
];

const List<Color> beerColors = [
  Color(0xfff3eb8f), // [0]
  Color(0xfffab123), // [1]
  Color(0xffca6100), // [2]
  Color(0xff8d4c32), // [3]
  Color(0xff180c0b), // [4]
  Color(0xffba0109), // [5]
  Color(0xff5bba01), // [6]
];

const defaultBeerColor = Color(0xfffab123);
