import "dart:ui";
import "package:my_beer_diary/model/beer.dart";

const List<String> breweryNames = [
  "Neznámý pivovar",
  "Agent",
  "Albert Michler",
  "Albrecht",
  "Antonín",
  "Antoš",
  "Bad Flash",
  "Bakalář",
  "Beer Factory",
  "Beran",
  "Bernard",
  "Bezák",
  "Bitches Brew",
  "Bizon",
  "Bohemia Regent",
  "Born",
  "Braník",
  "Brewteam",
  "Břevnov",
  "Březňák",
  "Budulínek",
  "Budweiser Budvar",
  "Clock",
  "Cobolis",
  "Crazy Clown",
  "Cvikov",
  "Čestmír",
  "Černá Hora",
  "Černý Potoka",
  "Čtyři lípy",
  "Dobruška",
  "Dobřany",
  "Dráteník",
  "Duck and Dog",
  "Elektrárna",
  "Excelent",
  "Falkenštejn",
  "Falkon",
  "Fenetra",
  "Frankies",
  "Funky Fluid",
  "Gambrinus",
  "GARP",
  "Hangár",
  "Hákův parní pivovar",
  "Hauskrecht",
  "Heineken",
  "Hellstork",
  "Hendrych",
  "Herold",
  "Holba",
  "Holendr",
  "Hoppy Dog",
  "Hostomice",
  "Hroch",
  "Hubertus",
  "Chomout",
  "Chotěšov",
  "Chotoviny",
  "Chroust",
  "ISAO",
  "Ježek",
  "Jungberg",
  "Kamenice",
  "Klasik",
  "Klášter",
  "Klenot",
  "Knajzl",
  "Kocour",
  "Kočovný Kozi",
  "Kojetín",
  "Konrad",
  "Kosa Prérií",
  "Kostelec",
  "Kotouč",
  "Kounice",
  "Kousek Piva",
  "Kozel",
  "Kozlíček Dubenky",
  "Krakonoš",
  "Krasavec",
  "Kristýna",
  "Kročehlavy",
  "Krušnohor",
  "Krušovice",
  "Křemenný Vrch",
  "Křikloun",
  "Kvasar",
  "Labuť",
  "Litovel",
  "Lípák",
  "Lobkowicz",
  "Lomnice",
  "Mad Cat",
  "Malešov",
  "Matuška",
  "Master",
  "Mazák",
  "Máša",
  "Medvěd",
  "Mlýn",
  "Moravia",
  "Mordýř",
  "Muflon",
  "Nachmelená Opice",
  "Nepomucen",
  "Nomád",
  "Novopacké",
  "Nový rybník",
  "Nozib",
  "Obora",
  "Olešná",
  "Opat",
  "O.SKAR",
  "Ostravar",
  "Ovipistán",
  "Pardál",
  "Paskov",
  "Perlová Voda",
  "Pernštejn",
  "Pilsner Urquell",
  "Pinta",
  "Pioneer",
  "Pivečka",
  "Platan",
  "Plzeňský Bandita",
  "Poděbradský Zdroj",
  "Podklášterní Urban",
  "Podřipské",
  "Polička",
  "Postřižiny",
  "Potmehúd",
  "Poutník",
  "Proud",
  "Primátor",
  "Primus",
  "Purkmistr",
  "Radegast",
  "Radouš",
  "Raven",
  "Rebel",
  "Rockmill",
  "Rohozec",
  "Rudohor",
  "Rychtář",
  "Řeporyje",
  "Samson",
  "Sibeeria",
  "SQBRU",
  "Starobrno",
  "Staropramen",
  "Stella Artois",
  "Stín",
  "Strahov",
  "Svatý Ján",
  "Svatý Petr",
  "Svijany",
  "Šepťák",
  "Švihov",
  "Tambor",
  "The Barn Beer co.",
  "Thrills",
  "Továrna",
  "Topolský",
  "Trilobit",
  "Třebonický Rukodělný",
  "U Fleků",
  "U Medvídků",
  "U Vacků",
  "Únětice",
  "Vagabund",
  "Valášek",
  "Valeč",
  "Valteřickej Strojník",
  "Veselka",
  "Vik",
  "Vinohradská",
  "Vinohradský Démon",
  "Volt",
  "Všerad",
  "Welzl",
  "Wywar",
  "Záhora",
  "Zdislavka",
  "Zhůřák",
  "Zichovec",
  "Zlatopramen",
  "Zlatý Bažant",
  "Zloun z Loun",
  "Zlosyn z Losin",
  "Znojemský Městský",
  "Zubr",
  "Zvíkov",
  "Žatec",
  "Židovice",
  "Žlebské Chvalovice",
];

const appColorSeed = Color(0xfff5ddb1);
const appColorSurface = Color(0xfffffefa);
const appColorContainer = Color(0xffffffff);
const appColorDisabledFAB = Color(0xffcfcec9);

const appColorInverseSurface = Color(0xff353027);
const appColorDisabled = Color(0xffaaa7a2);
const appColorPrimary = Color(0xff785a0b);
const appColorPrimaryContainer = Color(0xffffdf9f);
const appColorSecondary = Color(0xff6b5c3f);

const beerColorStraw = Color(0xfff3eb8f);
const beerColorGold = Color(0xfffec95a);
const beerColorAmber = Color(0xffd67100);
const beerColorBrown = Color(0xff8d4c32);
const beerColorDark = Color(0xff1e0204);
const beerColorRed = Color(0xffba0109);
const beerColorGreen = Color(0xff5bba01);

const List<Color> beerColors = [
  beerColorStraw,
  beerColorGold,
  beerColorAmber,
  beerColorBrown,
  beerColorDark,
  beerColorRed,
  beerColorGreen,
];

const beerColorStrawStr = "f3eb8f";
const beerColorGoldStr = "fec95a";
const beerColorAmberStr = "d67100";
const beerColorBrownStr = "8d4c32";
const beerColorDarkStr = "1e0204";
//const beerColorRedStr = "ba0109";
//const beerColorGreenStr = "5bba01";

const List<Beer> defaultBeers = [
  Beer(
    breweryName: "Beran",
    description: "Lehký ALE",
    epm: 10.0,
    abv: 4.5,
    color: beerColorAmberStr,
  ),
  Beer(
    breweryName: "Beran",
    description: "Jedenáctka",
    epm: 11.0,
    abv: 4.5,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Beran",
    description: "Polotmavá dvanáctka",
    epm: 12.0,
    abv: 5.0,
    color: beerColorBrownStr,
  ),
  Beer(
    breweryName: "Bernard",
    description: "Desítka",
    epm: 10.0,
    abv: 3.8,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Bernard",
    description: "Jedenáctka",
    epm: 11.0,
    abv: 4.5,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Bernard",
    description: "Kvasnicová jedenáctka",
    epm: 11.0,
    abv: 4.6,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Bernard",
    description: "Dvanáctka",
    epm: 12.0,
    abv: 4.9,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Braník",
    description: "Světlý",
    epm: 10.0,
    abv: 4.1,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Braník",
    description: "Jedenáctka",
    epm: 11.0,
    abv: 5.0,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Braník",
    description: "Ležák",
    epm: 12.0,
    abv: 5.2,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Budweiser Budvar",
    description: "Original",
    epm: 12.0,
    abv: 5.0,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Budweiser Budvar",
    description: "33",
    epm: 11.3,
    abv: 4.6,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Cvikov",
    description: "Sklář",
    epm: 8.6,
    abv: 3.5,
    color: beerColorStrawStr,
  ),
  Beer(
    breweryName: "Cvikov",
    description: "Luž",
    epm: 10.4,
    abv: 4.2,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Cvikov",
    description: "Hvozd",
    epm: 11.1,
    abv: 4.5,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Cvikov",
    description: "Klíč",
    epm: 12.4,
    abv: 4.8,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Cvikov",
    description: "Sváteční",
    epm: 13.6,
    abv: 5.6,
    color: beerColorBrownStr,
  ),
  Beer(
    breweryName: "Falkenštejn",
    description: "Světák",
    epm: 11.0,
    abv: 4.5,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Falkenštejn",
    description: "Ostroff",
    epm: 12.0,
    abv: 4.8,
    color: beerColorBrownStr,
  ),
  Beer(
    breweryName: "Falkenštejn",
    description: "Dittrich",
    epm: 14.0,
    abv: 5.5,
    color: beerColorDarkStr,
  ),
  Beer(
    breweryName: "Falkenštejn",
    description: "Svižnej Emil, APA",
    epm: 9.0,
    abv: 3.4,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Falkenštejn",
    description: "Deset!",
    epm: 10.0,
    abv: 3.9,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Falkenštejn",
    description: "Desperát, APA",
    epm: 11.0,
    abv: 4.8,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Falkenštejn",
    description: "Rudoch, American Amber Ale",
    epm: 13.0,
    abv: 5.4,
    color: beerColorAmberStr,
  ),
  Beer(
    breweryName: "Kozel",
    description: "10",
    epm: 10.0,
    abv: 4.2,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Kozel",
    description: "11",
    epm: 11.0,
    abv: 4.6,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Kozel",
    description: "12",
    epm: 12.0,
    abv: 5.1,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Kozel",
    description: "Černý",
    epm: 10.0,
    abv: 3.6,
    color: beerColorDarkStr,
  ),
  Beer(
    breweryName: "Kozel",
    description: "Řezaný",
    epm: 11.0,
    abv: 4.7,
    color: beerColorBrownStr,
  ),
  Beer(
    breweryName: "Pilsner Urquell",
    description: "",
    epm: 11.8,
    abv: 4.4,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Proud",
    description: "",
    epm: 11.3,
    abv: 3.9,
    color: beerColorStrawStr,
  ),
  Beer(
    breweryName: "Svijany",
    description: "Máz",
    epm: 11.0,
    abv: 4.8,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Svijany",
    description: "450",
    epm: 11.0,
    abv: 4.6,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Svijany",
    description: "Fanda",
    epm: 11.0,
    abv: 4.8,
    color: beerColorBrownStr,
  ),
  Beer(
    breweryName: "Svijany",
    description: "Rytíř",
    epm: 12.0,
    abv: 5.0,
    color: beerColorGoldStr,
  ),
  Beer(
    breweryName: "Svijany",
    description: "Kvasničák",
    epm: 13.0,
    abv: 6.0,
    color: beerColorGoldStr,
  ),
];
